name: testmw
favicon: null
layout_spectrum: 0.7429
typography_spectrum: 0.83555
title: Cake Lovers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
